/*
 * File: app/view/MyDataView11.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.view.MyDataView11', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.mydataview11',

    requires: [
        'Ext.field.Radio'
    ],

    config: {
        height: '100%',
        store: 'formStaticField',
        useComponents: true,
        itemConfig: {
            xtype: 'component',
            itemId: 'name'
        },
        items: [
            {
                xtype: 'radiofield',
                label: 'Field'
            }
        ]
    },

    updateRecord: function(reocrd) {
        console.log(record);
        // Provide an implementation to update this container's child items
            var button = this.down('radiofield');
            button.setLabel(record.get('extraParam'));
         //   button.setAge(record.get('age'));
    }

});