/*
 * File: app/store/allMsgStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.store.allMsgStore', {
    extend: 'Ext.data.Store',

    requires: [
        'tekwave.model.allMsgList'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                msgId: '',
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'red'
            },
            {
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'green'
            },
            {
                msgId: '',
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'blue'
            },
            {
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'yellow'
            },
            {
                msgId: '',
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'red'
            },
            {
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'green'
            },
            {
                msgId: '',
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'blue'
            },
            {
                senderName: 'Adam',
                msg: 'Hey Whats up, whats going on ....',
                time: '12:30PM',
                icon: 'img/img/arrow_right.png',
                leftColor: 'yellow'
            }
        ],
        model: 'tekwave.model.allMsgList',
        storeId: 'allMsgStore'
    }
});