/*
 * File: app/store/commStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.store.commStore', {
    extend: 'Ext.data.Store',

    requires: [
        'tekwave.model.homeModel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                data1: '<br/>',
                icon: 'img/img/icon_messages.png',
                name: '5 Messages',
                type: 'Messages',
                nextScreen: 'allMsgCont'
            },
            {
                data1: '<br/>',
                icon: 'img/img/icon_announcements.png',
                name: '2 New',
                type: 'Announcements',
                nextScreen: 'announsMentsCont'
            },
            {
                data1: '<br/>',
                icon: 'img/img/icon_messages.png',
                name: '5 Messages',
                type: 'Messages'
            },
            {
                data1: '<br/>',
                icon: 'img/img/icon_announcements.png',
                name: '2 New',
                type: 'Announcements'
            },
            
        ],
        model: 'tekwave.model.homeModel',
        storeId: 'commStore'
    }
});