/*
 * File: app/store/dailyTask.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.store.dailyTask', {
    extend: 'Ext.data.Store',

    requires: [
        'tekwave.model.homeModel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                data1: '<br/>',
                icon: 'img/img/icon_graph.png',
                name: 'Form',
                type: 'Task 1'
            },
            {
                data1: '<br/>',
                icon: 'img/img/icon_share.png',
                name: 'Form',
                type: 'Task 2'
            },
            {
                data1: '<br/>',
                icon: 'img/img/icon_graph.png',
                name: 'Form',
                type: 'Task 3'
            },
            {
                data1: '<br/>',
                icon: 'img/img/icon_share.png',
                name: 'Form',
                type: 'Task 4'
            }
        ],
        model: 'tekwave.model.homeModel',
        storeId: 'dailyTask'
    }
});