/*
 * File: app/store/menuStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.store.menuStore', {
    extend: 'Ext.data.Store',

    requires: [
        'tekwave.model.menuModel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                /* id : 1, */menuName: 'Home',
                icon: 'img/img/icon_home.png',
                nextScreen: 'homeCont',
                leftColor: 'green'
            },
            {
                /* id :2, */menuName: 'Setting',
                icon: 'img/img/icon_settings.png',
                nextScreen: 'settingsCont',
                leftColor: 'blue'
            },
            {
                /* id : 1, */menuName: 'Static Forms',
                icon: 'img/img/icon_static_form.png',
                nextScreen: 'staticFormCont',
                leftColor: 'red'
            },
            {
                /* id :2, */menuName: 'Dynamic Forms',
                icon: 'img/img/icon_dynamic_form.png',
                nextScreen: 'dynamicForm',
                leftColor: 'yellow'
            },
            {
                /* id : 1, */menuName: 'Switch User',
                icon: 'img/img/icon_swith_user.png',
                nextScreen: 'switchUser',
                leftColor: 'green'
            },
            {
                /* id :2, */menuName: 'Sites/Posts',
                icon: 'img/img/icon_sites.png',
                nextScreen: 'sitePostCont',
                leftColor: 'blue'
            },
            {
                /* id :2, */menuName: 'Logout',
                icon: 'img/img/icon_logout.png',
                nextScreen: 'signInCont',
                leftColor: 'red'
            }
        ],
        model: 'tekwave.model.menuModel',
        storeId: 'menuStore'
    }
});