/*
 * File: app/store/MyXmlStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.store.MyXmlStore', {
    extend: 'Ext.data.Store',

    requires: [
        'tekwave.model.homeModel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                id: 1,
                data1: 'Tuesday 6/10/14',
                icon: 'img/img/icon_weather.png',
                name: 'Cloudy 23°',
                type: 'Wheather'
            },
            {
                id: 2,
                data1: 'Tuesday 6/10/14',
                icon: 'img/img/icon_clock.png',
                name: '5:00 PM',
                type: 'Time'
            },
            {
                id: 3,
                data1: 'Tuesday 6/10/14',
                icon: 'img/img/icon_weather.png',
                name: 'Cloudy 23°',
                type: 'Wheather'
            },
            {
                id: 4,
                data1: 'Tuesday 6/10/14',
                icon: 'img/img/icon_clock.png',
                name: '5:00 PM',
                type: 'Time'
            }
        ],
        model: 'tekwave.model.homeModel',
        storeId: 'MyXmlStore'
    }
});