/*
 * File: app/store/oneToOneChat.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.store.oneToOneChat', {
    extend: 'Ext.data.Store',

    requires: [
        'tekwave.model.chatmodel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                msg: 'Hey whats up, whats going on !',
                senderid: 'jhon',
                reciverid: 'adam'
            },
            {
                msg: 'Hello',
                senderid: 'adam',
                reciverid: 'jhon'
            },
            {
                msg: 'Hey whats up, whats going on !',
                senderid: 'jhon',
                reciverid: 'adam'
            },
            {
                msg: 'Hey whats up, whats going on ! ',
                senderid: 'adam',
                reciverid: 'jhon'
            }
        ],
        model: 'tekwave.model.chatmodel',
        storeId: 'oneToOneChat'
    }
});