/*
 * File: app/store/sitePost.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.store.sitePost', {
    extend: 'Ext.data.Store',

    requires: [
        'tekwave.model.menuModel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                /* id : 1, */menuName: 'Able',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'home',
                leftColor: 'green'
            },
            {
                /* id :2, */menuName: 'Setting',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'settings',
                leftColor: 'blue'
            },
            {
                /* id : 1, */menuName: 'Affluent',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'staticForm',
                leftColor: 'red'
            },
            {
                /* id :2, */menuName: 'Amped',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'dynamicForm',
                leftColor: 'yellow'
            },
            {
                /* id : 1, */menuName: 'Another',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'switchUser',
                leftColor: 'green'
            },
            {
                /* id :2, */menuName: 'Bait',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'sitePost',
                leftColor: 'blue'
            },
            {
                /* id :2, */menuName: 'Blunder',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'logout',
                leftColor: 'red'
            },
            {
                /* id :2, */menuName: 'Brush',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'sitePost',
                leftColor: 'blue'
            },
            {
                /* id :2, */menuName: 'Brother',
                icon: 'img/img/arrow_right.png',
                nextScreen: 'logout',
                leftColor: 'red'
            }
        ],
        model: 'tekwave.model.menuModel',
        storeId: 'sitePost'
    }
});