/*
 * File: app/model/formModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('tekwave.model.formModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'type'
            },
            {
                name: 'lable'
            },
            {
                name: 'placeHolder'
            },
            {
                name: 'checked'
            },
            {
                name: 'section'
            },
            {
                name: 'formField'
            },
            {
                name: 'formName'
            },
            {
                name: 'formId'
            },
            {
                name: 'allfieldData'
            },
            {
                name: 'radioName'
            },
            {
                name: 'leftColor'
            },
            {
                name: 'quickLinkScreen'
            },
            {
                name: 'isQuickLink'
            }
        ]
    }
});